//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedidosWin.ArticulosServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ArticulosServiceReference.IArticulos")]
    public interface IArticulos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArticulos/CrearArticulo", ReplyAction="http://tempuri.org/IArticulos/CrearArticuloResponse")]
        SOAPServices.Dominio.Articulo CrearArticulo(string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArticulos/CrearArticulo", ReplyAction="http://tempuri.org/IArticulos/CrearArticuloResponse")]
        System.Threading.Tasks.Task<SOAPServices.Dominio.Articulo> CrearArticuloAsync(string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArticulos/ObtenerArticulo", ReplyAction="http://tempuri.org/IArticulos/ObtenerArticuloResponse")]
        SOAPServices.Dominio.Articulo ObtenerArticulo(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArticulos/ObtenerArticulo", ReplyAction="http://tempuri.org/IArticulos/ObtenerArticuloResponse")]
        System.Threading.Tasks.Task<SOAPServices.Dominio.Articulo> ObtenerArticuloAsync(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArticulos/ModificarArticulo", ReplyAction="http://tempuri.org/IArticulos/ModificarArticuloResponse")]
        SOAPServices.Dominio.Articulo ModificarArticulo(int codigo, string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArticulos/ModificarArticulo", ReplyAction="http://tempuri.org/IArticulos/ModificarArticuloResponse")]
        System.Threading.Tasks.Task<SOAPServices.Dominio.Articulo> ModificarArticuloAsync(int codigo, string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArticulos/EliminarArticulo", ReplyAction="http://tempuri.org/IArticulos/EliminarArticuloResponse")]
        void EliminarArticulo(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArticulos/EliminarArticulo", ReplyAction="http://tempuri.org/IArticulos/EliminarArticuloResponse")]
        System.Threading.Tasks.Task EliminarArticuloAsync(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArticulos/ListarArticulos", ReplyAction="http://tempuri.org/IArticulos/ListarArticulosResponse")]
        SOAPServices.Dominio.Articulo[] ListarArticulos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArticulos/ListarArticulos", ReplyAction="http://tempuri.org/IArticulos/ListarArticulosResponse")]
        System.Threading.Tasks.Task<SOAPServices.Dominio.Articulo[]> ListarArticulosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IArticulosChannel : PedidosWin.ArticulosServiceReference.IArticulos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ArticulosClient : System.ServiceModel.ClientBase<PedidosWin.ArticulosServiceReference.IArticulos>, PedidosWin.ArticulosServiceReference.IArticulos {
        
        public ArticulosClient() {
        }
        
        public ArticulosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ArticulosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ArticulosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ArticulosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SOAPServices.Dominio.Articulo CrearArticulo(string descripcion) {
            return base.Channel.CrearArticulo(descripcion);
        }
        
        public System.Threading.Tasks.Task<SOAPServices.Dominio.Articulo> CrearArticuloAsync(string descripcion) {
            return base.Channel.CrearArticuloAsync(descripcion);
        }
        
        public SOAPServices.Dominio.Articulo ObtenerArticulo(int codigo) {
            return base.Channel.ObtenerArticulo(codigo);
        }
        
        public System.Threading.Tasks.Task<SOAPServices.Dominio.Articulo> ObtenerArticuloAsync(int codigo) {
            return base.Channel.ObtenerArticuloAsync(codigo);
        }
        
        public SOAPServices.Dominio.Articulo ModificarArticulo(int codigo, string descripcion) {
            return base.Channel.ModificarArticulo(codigo, descripcion);
        }
        
        public System.Threading.Tasks.Task<SOAPServices.Dominio.Articulo> ModificarArticuloAsync(int codigo, string descripcion) {
            return base.Channel.ModificarArticuloAsync(codigo, descripcion);
        }
        
        public void EliminarArticulo(int codigo) {
            base.Channel.EliminarArticulo(codigo);
        }
        
        public System.Threading.Tasks.Task EliminarArticuloAsync(int codigo) {
            return base.Channel.EliminarArticuloAsync(codigo);
        }
        
        public SOAPServices.Dominio.Articulo[] ListarArticulos() {
            return base.Channel.ListarArticulos();
        }
        
        public System.Threading.Tasks.Task<SOAPServices.Dominio.Articulo[]> ListarArticulosAsync() {
            return base.Channel.ListarArticulosAsync();
        }
    }
}
