//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedidosWin.StocksServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StocksServiceReference.IStocks")]
    public interface IStocks {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStocks/ObtenerStock", ReplyAction="http://tempuri.org/IStocks/ObtenerStockResponse")]
        SOAPServices.Dominio.Stock ObtenerStock(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStocks/ObtenerStock", ReplyAction="http://tempuri.org/IStocks/ObtenerStockResponse")]
        System.Threading.Tasks.Task<SOAPServices.Dominio.Stock> ObtenerStockAsync(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStocks/ModificarStock", ReplyAction="http://tempuri.org/IStocks/ModificarStockResponse")]
        SOAPServices.Dominio.Stock ModificarStock(int codigo, int nuevoStock);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStocks/ModificarStock", ReplyAction="http://tempuri.org/IStocks/ModificarStockResponse")]
        System.Threading.Tasks.Task<SOAPServices.Dominio.Stock> ModificarStockAsync(int codigo, int nuevoStock);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStocksChannel : PedidosWin.StocksServiceReference.IStocks, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StocksClient : System.ServiceModel.ClientBase<PedidosWin.StocksServiceReference.IStocks>, PedidosWin.StocksServiceReference.IStocks {
        
        public StocksClient() {
        }
        
        public StocksClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StocksClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StocksClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StocksClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SOAPServices.Dominio.Stock ObtenerStock(int codigo) {
            return base.Channel.ObtenerStock(codigo);
        }
        
        public System.Threading.Tasks.Task<SOAPServices.Dominio.Stock> ObtenerStockAsync(int codigo) {
            return base.Channel.ObtenerStockAsync(codigo);
        }
        
        public SOAPServices.Dominio.Stock ModificarStock(int codigo, int nuevoStock) {
            return base.Channel.ModificarStock(codigo, nuevoStock);
        }
        
        public System.Threading.Tasks.Task<SOAPServices.Dominio.Stock> ModificarStockAsync(int codigo, int nuevoStock) {
            return base.Channel.ModificarStockAsync(codigo, nuevoStock);
        }
    }
}
