//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedidosWin.VerificarRUCServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VerificarRUCServiceReference.IVerificaDocumento")]
    public interface IVerificaDocumento {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVerificaDocumento/VerificaRUC", ReplyAction="http://tempuri.org/IVerificaDocumento/VerificaRUCResponse")]
        bool VerificaRUC(string RUC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVerificaDocumento/VerificaRUC", ReplyAction="http://tempuri.org/IVerificaDocumento/VerificaRUCResponse")]
        System.Threading.Tasks.Task<bool> VerificaRUCAsync(string RUC);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVerificaDocumentoChannel : PedidosWin.VerificarRUCServiceReference.IVerificaDocumento, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VerificaDocumentoClient : System.ServiceModel.ClientBase<PedidosWin.VerificarRUCServiceReference.IVerificaDocumento>, PedidosWin.VerificarRUCServiceReference.IVerificaDocumento {
        
        public VerificaDocumentoClient() {
        }
        
        public VerificaDocumentoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VerificaDocumentoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VerificaDocumentoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VerificaDocumentoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool VerificaRUC(string RUC) {
            return base.Channel.VerificaRUC(RUC);
        }
        
        public System.Threading.Tasks.Task<bool> VerificaRUCAsync(string RUC) {
            return base.Channel.VerificaRUCAsync(RUC);
        }
    }
}
