//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedidosWin.PedidoDetallesWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PedidoDetallesWS.IPedidoDetalles")]
    public interface IPedidoDetalles {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidoDetalles/CrearPedidoDetalle", ReplyAction="http://tempuri.org/IPedidoDetalles/CrearPedidoDetalleResponse")]
        SOAPServices.Dominio.PedidoDetalle CrearPedidoDetalle(
                    int codCompania, 
                    int codSucursalCia, 
                    int ano, 
                    int numeroPedido, 
                    int numeroItem, 
                    int codItemArticulo, 
                    int unidadesPedidas, 
                    int unidadesComprometidas, 
                    double importePrecioUnitarioSIGV, 
                    double importePrecioUnitarioCIGV, 
                    double importeSubtotalBruto, 
                    double porcentajeDescuento, 
                    double importeSubtotalDescuento, 
                    double importeSubtotalNeto, 
                    int codEstadoAtencion, 
                    int codEstadoRegistro, 
                    string codUsuarioCreador, 
                    System.DateTime fecCreacion, 
                    string codUsuarioUpdate, 
                    System.DateTime fecUpdate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidoDetalles/CrearPedidoDetalle", ReplyAction="http://tempuri.org/IPedidoDetalles/CrearPedidoDetalleResponse")]
        System.Threading.Tasks.Task<SOAPServices.Dominio.PedidoDetalle> CrearPedidoDetalleAsync(
                    int codCompania, 
                    int codSucursalCia, 
                    int ano, 
                    int numeroPedido, 
                    int numeroItem, 
                    int codItemArticulo, 
                    int unidadesPedidas, 
                    int unidadesComprometidas, 
                    double importePrecioUnitarioSIGV, 
                    double importePrecioUnitarioCIGV, 
                    double importeSubtotalBruto, 
                    double porcentajeDescuento, 
                    double importeSubtotalDescuento, 
                    double importeSubtotalNeto, 
                    int codEstadoAtencion, 
                    int codEstadoRegistro, 
                    string codUsuarioCreador, 
                    System.DateTime fecCreacion, 
                    string codUsuarioUpdate, 
                    System.DateTime fecUpdate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidoDetalles/ObtenerPedidoDetalle", ReplyAction="http://tempuri.org/IPedidoDetalles/ObtenerPedidoDetalleResponse")]
        SOAPServices.Dominio.PedidoDetalle ObtenerPedidoDetalle(int numeroItem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidoDetalles/ObtenerPedidoDetalle", ReplyAction="http://tempuri.org/IPedidoDetalles/ObtenerPedidoDetalleResponse")]
        System.Threading.Tasks.Task<SOAPServices.Dominio.PedidoDetalle> ObtenerPedidoDetalleAsync(int numeroItem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidoDetalles/ModificarPedidoDetalle", ReplyAction="http://tempuri.org/IPedidoDetalles/ModificarPedidoDetalleResponse")]
        SOAPServices.Dominio.PedidoDetalle ModificarPedidoDetalle(
                    int numeroItem, 
                    int codCompania, 
                    int codSucursalCia, 
                    int ano, 
                    int numeroPedido, 
                    int codItemArticulo, 
                    int unidadesPedidas, 
                    int unidadesComprometidas, 
                    double importePrecioUnitarioSIGV, 
                    double importePrecioUnitarioCIGV, 
                    double importeSubtotalBruto, 
                    double porcentajeDescuento, 
                    double importeSubtotalDescuento, 
                    double importeSubtotalNeto, 
                    int codEstadoAtencion, 
                    int codEstadoRegistro, 
                    string codUsuarioCreador, 
                    System.DateTime fecCreacion, 
                    string codUsuarioUpdate, 
                    System.DateTime fecUpdate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidoDetalles/ModificarPedidoDetalle", ReplyAction="http://tempuri.org/IPedidoDetalles/ModificarPedidoDetalleResponse")]
        System.Threading.Tasks.Task<SOAPServices.Dominio.PedidoDetalle> ModificarPedidoDetalleAsync(
                    int numeroItem, 
                    int codCompania, 
                    int codSucursalCia, 
                    int ano, 
                    int numeroPedido, 
                    int codItemArticulo, 
                    int unidadesPedidas, 
                    int unidadesComprometidas, 
                    double importePrecioUnitarioSIGV, 
                    double importePrecioUnitarioCIGV, 
                    double importeSubtotalBruto, 
                    double porcentajeDescuento, 
                    double importeSubtotalDescuento, 
                    double importeSubtotalNeto, 
                    int codEstadoAtencion, 
                    int codEstadoRegistro, 
                    string codUsuarioCreador, 
                    System.DateTime fecCreacion, 
                    string codUsuarioUpdate, 
                    System.DateTime fecUpdate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidoDetalles/EliminarPedidoDetalle", ReplyAction="http://tempuri.org/IPedidoDetalles/EliminarPedidoDetalleResponse")]
        void EliminarPedidoDetalle(int numeroItem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidoDetalles/EliminarPedidoDetalle", ReplyAction="http://tempuri.org/IPedidoDetalles/EliminarPedidoDetalleResponse")]
        System.Threading.Tasks.Task EliminarPedidoDetalleAsync(int numeroItem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidoDetalles/ListarPedidoDetalle", ReplyAction="http://tempuri.org/IPedidoDetalles/ListarPedidoDetalleResponse")]
        SOAPServices.Dominio.PedidoDetalle[] ListarPedidoDetalle();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidoDetalles/ListarPedidoDetalle", ReplyAction="http://tempuri.org/IPedidoDetalles/ListarPedidoDetalleResponse")]
        System.Threading.Tasks.Task<SOAPServices.Dominio.PedidoDetalle[]> ListarPedidoDetalleAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPedidoDetallesChannel : PedidosWin.PedidoDetallesWS.IPedidoDetalles, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PedidoDetallesClient : System.ServiceModel.ClientBase<PedidosWin.PedidoDetallesWS.IPedidoDetalles>, PedidosWin.PedidoDetallesWS.IPedidoDetalles {
        
        public PedidoDetallesClient() {
        }
        
        public PedidoDetallesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PedidoDetallesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PedidoDetallesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PedidoDetallesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SOAPServices.Dominio.PedidoDetalle CrearPedidoDetalle(
                    int codCompania, 
                    int codSucursalCia, 
                    int ano, 
                    int numeroPedido, 
                    int numeroItem, 
                    int codItemArticulo, 
                    int unidadesPedidas, 
                    int unidadesComprometidas, 
                    double importePrecioUnitarioSIGV, 
                    double importePrecioUnitarioCIGV, 
                    double importeSubtotalBruto, 
                    double porcentajeDescuento, 
                    double importeSubtotalDescuento, 
                    double importeSubtotalNeto, 
                    int codEstadoAtencion, 
                    int codEstadoRegistro, 
                    string codUsuarioCreador, 
                    System.DateTime fecCreacion, 
                    string codUsuarioUpdate, 
                    System.DateTime fecUpdate) {
            return base.Channel.CrearPedidoDetalle(codCompania, codSucursalCia, ano, numeroPedido, numeroItem, codItemArticulo, unidadesPedidas, unidadesComprometidas, importePrecioUnitarioSIGV, importePrecioUnitarioCIGV, importeSubtotalBruto, porcentajeDescuento, importeSubtotalDescuento, importeSubtotalNeto, codEstadoAtencion, codEstadoRegistro, codUsuarioCreador, fecCreacion, codUsuarioUpdate, fecUpdate);
        }
        
        public System.Threading.Tasks.Task<SOAPServices.Dominio.PedidoDetalle> CrearPedidoDetalleAsync(
                    int codCompania, 
                    int codSucursalCia, 
                    int ano, 
                    int numeroPedido, 
                    int numeroItem, 
                    int codItemArticulo, 
                    int unidadesPedidas, 
                    int unidadesComprometidas, 
                    double importePrecioUnitarioSIGV, 
                    double importePrecioUnitarioCIGV, 
                    double importeSubtotalBruto, 
                    double porcentajeDescuento, 
                    double importeSubtotalDescuento, 
                    double importeSubtotalNeto, 
                    int codEstadoAtencion, 
                    int codEstadoRegistro, 
                    string codUsuarioCreador, 
                    System.DateTime fecCreacion, 
                    string codUsuarioUpdate, 
                    System.DateTime fecUpdate) {
            return base.Channel.CrearPedidoDetalleAsync(codCompania, codSucursalCia, ano, numeroPedido, numeroItem, codItemArticulo, unidadesPedidas, unidadesComprometidas, importePrecioUnitarioSIGV, importePrecioUnitarioCIGV, importeSubtotalBruto, porcentajeDescuento, importeSubtotalDescuento, importeSubtotalNeto, codEstadoAtencion, codEstadoRegistro, codUsuarioCreador, fecCreacion, codUsuarioUpdate, fecUpdate);
        }
        
        public SOAPServices.Dominio.PedidoDetalle ObtenerPedidoDetalle(int numeroItem) {
            return base.Channel.ObtenerPedidoDetalle(numeroItem);
        }
        
        public System.Threading.Tasks.Task<SOAPServices.Dominio.PedidoDetalle> ObtenerPedidoDetalleAsync(int numeroItem) {
            return base.Channel.ObtenerPedidoDetalleAsync(numeroItem);
        }
        
        public SOAPServices.Dominio.PedidoDetalle ModificarPedidoDetalle(
                    int numeroItem, 
                    int codCompania, 
                    int codSucursalCia, 
                    int ano, 
                    int numeroPedido, 
                    int codItemArticulo, 
                    int unidadesPedidas, 
                    int unidadesComprometidas, 
                    double importePrecioUnitarioSIGV, 
                    double importePrecioUnitarioCIGV, 
                    double importeSubtotalBruto, 
                    double porcentajeDescuento, 
                    double importeSubtotalDescuento, 
                    double importeSubtotalNeto, 
                    int codEstadoAtencion, 
                    int codEstadoRegistro, 
                    string codUsuarioCreador, 
                    System.DateTime fecCreacion, 
                    string codUsuarioUpdate, 
                    System.DateTime fecUpdate) {
            return base.Channel.ModificarPedidoDetalle(numeroItem, codCompania, codSucursalCia, ano, numeroPedido, codItemArticulo, unidadesPedidas, unidadesComprometidas, importePrecioUnitarioSIGV, importePrecioUnitarioCIGV, importeSubtotalBruto, porcentajeDescuento, importeSubtotalDescuento, importeSubtotalNeto, codEstadoAtencion, codEstadoRegistro, codUsuarioCreador, fecCreacion, codUsuarioUpdate, fecUpdate);
        }
        
        public System.Threading.Tasks.Task<SOAPServices.Dominio.PedidoDetalle> ModificarPedidoDetalleAsync(
                    int numeroItem, 
                    int codCompania, 
                    int codSucursalCia, 
                    int ano, 
                    int numeroPedido, 
                    int codItemArticulo, 
                    int unidadesPedidas, 
                    int unidadesComprometidas, 
                    double importePrecioUnitarioSIGV, 
                    double importePrecioUnitarioCIGV, 
                    double importeSubtotalBruto, 
                    double porcentajeDescuento, 
                    double importeSubtotalDescuento, 
                    double importeSubtotalNeto, 
                    int codEstadoAtencion, 
                    int codEstadoRegistro, 
                    string codUsuarioCreador, 
                    System.DateTime fecCreacion, 
                    string codUsuarioUpdate, 
                    System.DateTime fecUpdate) {
            return base.Channel.ModificarPedidoDetalleAsync(numeroItem, codCompania, codSucursalCia, ano, numeroPedido, codItemArticulo, unidadesPedidas, unidadesComprometidas, importePrecioUnitarioSIGV, importePrecioUnitarioCIGV, importeSubtotalBruto, porcentajeDescuento, importeSubtotalDescuento, importeSubtotalNeto, codEstadoAtencion, codEstadoRegistro, codUsuarioCreador, fecCreacion, codUsuarioUpdate, fecUpdate);
        }
        
        public void EliminarPedidoDetalle(int numeroItem) {
            base.Channel.EliminarPedidoDetalle(numeroItem);
        }
        
        public System.Threading.Tasks.Task EliminarPedidoDetalleAsync(int numeroItem) {
            return base.Channel.EliminarPedidoDetalleAsync(numeroItem);
        }
        
        public SOAPServices.Dominio.PedidoDetalle[] ListarPedidoDetalle() {
            return base.Channel.ListarPedidoDetalle();
        }
        
        public System.Threading.Tasks.Task<SOAPServices.Dominio.PedidoDetalle[]> ListarPedidoDetalleAsync() {
            return base.Channel.ListarPedidoDetalleAsync();
        }
    }
}
